services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: seblm-database-password
      POSTGRES_USER: seblm-meals
    volumes:
      - data:/var/lib/postgresql/data
  application:
    build: target/docker/stage
    image: seblm-meals
    depends_on:
      - database
    environment:
      POSTGRESQL_ADDON_USER: seblm-meals
      POSTGRESQL_ADDON_PASSWORD: seblm-database-password
      POSTGRESQL_ADDON_HOST: database
      POSTGRESQL_ADDON_DB: seblm-meals
      APPLICATION_SECRET: ziN0JiGEzE6FvUBddNcEttAC/WdabutXXblfzusCQSs=
    ports:
      - 9000:9000
volumes:
  data:
