name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: coursier/cache-action@v6
      - name: Check Scalafmt
        continue-on-error: true
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
